export const TEAMS = [
  { abbr: "ANA", name: "Anaheim Ducks" },
  { abbr: "BOS", name: "Boston Bruins" },
  { abbr: "BUF", name: "Buffalo Sabres" },
  { abbr: "CGY", name: "Calgary Flames" },
  { abbr: "CAR", name: "Carolina Hurricanes" },
  { abbr: "CHI", name: "Chicago Blackhawks" },
  { abbr: "COL", name: "Colorado Avalanche" },
  { abbr: "CBJ", name: "Columbus Blue Jackets" },
  { abbr: "DAL", name: "Dallas Stars" },
  { abbr: "DET", name: "Detroit Red Wings" },
  { abbr: "EDM", name: "Edmonton Oilers" },
  { abbr: "FLA", name: "Florida Panthers" },
  { abbr: "LAK", name: "Los Angeles Kings" },
  { abbr: "MIN", name: "Minnesota Wild" },
  { abbr: "MTL", name: "Montréal Canadiens" },
  { abbr: "NSH", name: "Nashville Predators" },
  { abbr: "NJD", name: "New Jersey Devils" },
  { abbr: "NYI", name: "New York Islanders" },
  { abbr: "NYR", name: "New York Rangers" },
  { abbr: "OTT", name: "Ottawa Senators" },
  { abbr: "PHI", name: "Philadelphia Flyers" },
  { abbr: "PIT", name: "Pittsburgh Penguins" },
  { abbr: "SJS", name: "San Jose Sharks" },
  { abbr: "SEA", name: "Seattle Kraken" },
  { abbr: "STL", name: "St. Louis Blues" },
  { abbr: "TBL", name: "Tampa Bay Lightning" },
  { abbr: "TOR", name: "Toronto Maple Leafs" },
  { abbr: "UTA", name: "Utah Mammoth" },
  { abbr: "VAN", name: "Vancouver Canucks" },
  { abbr: "VGK", name: "Vegas Golden Knights" },
  { abbr: "WSH", name: "Washington Capitals" },
  { abbr: "WPG", name: "Winnipeg Jets" },
];

export const TEAM_ABBRS = new Set(TEAMS.map((team) => team.abbr));
